apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-demo
spec:
  rules:
    - host: rancher-demo.$NUM.rancherfederal.training
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: rancher-demo
              port:
                name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
  labels:
    app.kubernetes.io/name: rancher-demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app.kubernetes.io/name: rancher-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rancher-demo
    spec:
      containers:
        - name: rancher-demo
          image: "zackbradys/rancher-demo-app:1.1.0"
          imagePullPolicy: Always
          env:
          - name: TITLE
            value: "Rancher Federal Demo App"
          - name: CONTAINER_COLOR
            value: "black"
          - name: PETS
            value: "cows"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {}
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-demo
  labels:
    app.kubernetes.io/name: rancher-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: rancher-demo